version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shoestore
    networks: 
      - webnet
  web:
    image: sneaker-server
    ports:
      - "8080:8080"
    networks: 
      - webnet
    environment: 
      DB_HOST: db
      REDIS_HOST: redis
    command: [node, index.js]
networks: 
  webnet: